#!/bin/bash

# Submit diagram calculations, using minos and form, to a cluster with
# one diagram per sge/pbs task.
# The following environment variables should be exported in env:
# -   FORMTMPROOT: base dir for scratch files. Folders created in here
# -   FORMPATH: directory containing procedures used by calcdia.frm etc

###############################################################################


# SGE
#$ -pe smp 16
#$ -l h_vmem=4000M
#$ -l h_rt=72:00:00
# #$ -l tmp_free=200G
#$ -cwd -V
#$ -m ae
#$ -M user@host
# blacklist a node?
# #$ -l h=!comp1
#$ -e runfiles/SETMEREAC/SETMEMOM/
#$ -o runfiles/SETMEREAC/SETMEMOM/
#$ -N SETMEREACSETMEMOM

#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -V
#PBS -m ae
#PBS -M user@host
#PBS -e runfiles/SETMEREAC/SETMEMOM/
#PBS -o runfiles/SETMEREAC/SETMEMOM/
#PBS -N SETMEREACSETMEMOM

if [ -n "$SGE_ROOT" ];
then
	TASKNUMBER=$SGE_TASK_ID
	echo Using SGE
	echo JobID: $JOB_NAME $TASKNUMBER
else
	cd $PBS_O_WORKDIR
	TASKNUMBER=$PBS_ARRAYID
	echo Using PBS
	echo JobID: $PBS_JOBNAME $TASKNUMBER
fi

export FORMPROCESSORS=16
export MINOSPROCESSORS=1
################################################################################

trap "echo error! Job terminating early: `date`" SIGINT SIGTERM SIGKILL

echo Running on host: $HOSTNAME
echo --- computing diagrams SETMEREAC $TASKNUMBER to $TASKNUMBER at N=SETMEMOM

SCRATCHDIR=$FORMTMPROOT/SETMEREAC/SETMEMOM/dia-$TASKNUMBER

# set up scratch space
mkdir -p $SCRATCHDIR
if [ ! -d $SCRATCHDIR ]
then
	echo Error, could not create scratch directory $SCRATCHDIR
	exit
fi
export FORMTMP=$SCRATCHDIR

# Set lustre striping if appropriate
if [ "$(df -T $SCRATCHDIR | grep -c lustre)" -eq 1 ]
then
	echo --- lustre scratch dir $SCRATCHDIR
	echo --- setting striping...
	lfs setstripe -c -1 $SCRATCHDIR
else
	echo --- with scratch dir $FORMTMP
fi

echo STARTTIME `date`
STARTSTAMP=`date +"%s"`

#################################################################################

# cd into working dir. submit scripts queued from above
cd runfiles/SETMEREAC/SETMEMOM/dia-$TASKNUMBER

while true; do du -s $FORMTMP >> diskuse.log; sleep 20; done &

# Start diagram calculation. Correct diagram range for minos
# has been set by script which creates the runfiles, ie, it fills
# in SETMEMOM, $TASKNUMBER, $TASKNUMBER
minos makeres

# remove scratch space - KEEP FILES ON CRASH FOR DEBUGGING PURPOSES.
#                        A CLEAN EXIT WILL LEAVE JUST AN EMPTY FOLDER.
#rm -r $SCRATCHDIR

kill $!

# print run times
echo ENDTIME `date`
ENDSTAMP=`date +"%s"`
echo RUNTIME: $(($ENDSTAMP-$STARTSTAMP))


